### ISSUE TITLE
Provide a set of bright color variants

### ISSUE THREAD

**Issue by d2718nis** [d2718nis/rose-pine-foot#7]
# The issue
In the current themes, most `bright` color variants are set to match the base colors. This limits the use of all 16 colors in the terminal color scheme, making it difficult to add accents or visual emphasis.
![screenshot-2024-10-30-19-22-39](https://github.com/user-attachments/assets/44cc03a2-ec31-4cde-bb7a-ae52abcede61)

## Context
While the official Rose Pine [palette](https://rosepinetheme.com/palette/) provides only base colors, there’s potential to modify these by adjusting brightness and saturation. Since this palette leans toward muted tones, the following could be applied:
- **Brightness Shift**: To make colors "brighter", increase the RGB values of each color by about 10-20%, depending on the specific color to add a visible difference
- **Saturation Boost**: Some colors (like the red and yellow) benefit from a slight (around 10-15%) saturation increase to make them appear more vibrant

> The original specification only had 8 colors, and just gave them names. The SGR parameters 30–37 selected the foreground color, while 40–47 selected the background. Quite a few terminals implemented "bold" (SGR code 1) as a brighter color rather than a different font, thus providing 8 additional foreground colors.
[ANSI Escape Code](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit)

## Example
I didn't decide on the final result of how much should each of the `bright` variants add to its brightness and saturation to have a noticeable difference but at the same time maintain the overall theme aesthetics. Here's an example of how it could look for the main rose-pine theme:
![screenshot-2024-10-30-19-44-01](https://github.com/user-attachments/assets/128d4e12-cd56-40e9-b179-c47709960a5c)

Slightly brighter option
![screenshot-2024-10-30-22-25-04](https://github.com/user-attachments/assets/15fd9598-9c32-4426-8adf-f8ef9f20d076)

## Dependencies
I'm waiting for #6 to be merged to create a pull request for this feature.

**Comment by d2718nis** [comment]
I was skimming through the other themes and `man 5 foot.ini` to check for any additional missing colors, and there’s at least one:
```ini
flash=7f7f00
```

This only activates when the following option is enabled (default is `no`):
```ini
[bell]
visual=yes
```

It could still be useful to assign a value for it. Since the default uses a yellowish tone, setting it to something like Gold seems like it would fit well.

Other color values are configurable, but most already draw from the existing palette (`regular1..7`), like:
```ini
[color]
selection-foreground=
selection-background=
jump-labels=
scrollback-indicator=
search-box-no-match=
search-box-match=
urls=
```

For `dim0..7`, foot has an internal algorithm to derive these from `regular0..7`:
> By  default,  foot  implements  this  by  reducing  the  luminance of the current color. This is a generic approach that applies to both colors from the 256-color palette, as well as 24-bit RGB colors.

**Comment by d2718nis** [comment]
I feel like this could be the end result

**Rose Pine**
![screenshot-2024-11-01-02-57-10](https://github.com/user-attachments/assets/465cb3d6-4004-44be-b5ee-00d62c28cf80)
```ini
bright0=3b3750      # bright black (lighter Overlay)
bright1=f48fa6      # bright red (lighter Love)
bright2=b6e2eb      # bright green (lighter Foam)
bright3=ffd89a      # bright yellow (lighter Gold)
bright4=4b93b0      # bright blue (lighter Pine)
bright5=d7b7f4      # bright magenta (lighter Iris)
bright6=ffcecc      # bright cyan (lighter Rose)
bright7=f5f4ff      # bright white (lighter Text)
```

**Rose Pine Moon**
![screenshot-2024-11-01-02-57-20](https://github.com/user-attachments/assets/e68e1832-84f1-4313-b612-e55e25ebb28f)
```ini
bright0=52486a      # bright black (lighter Overlay)
bright1=f48fa6      # bright red (lighter Love)
bright2=b6e2eb      # bright green (lighter Foam)
bright3=ffd89a      # bright yellow (lighter Gold)
bright4=5aa8cd      # bright blue (lighter Pine)
bright5=d7b7f4      # bright magenta (lighter Iris)
bright6=ffb1af      # bright cyan (lighter Rose)
bright7=f5f4ff      # bright white (lighter Text)
```

**Rose Pine Dawn**
![screenshot-2024-11-01-02-57-32](https://github.com/user-attachments/assets/9bd2c524-68be-4211-9f73-6232bb102ce7)
```ini
bright0=f7f1eb      # bright black (lighter Overlay)
bright1=c97c8d      # bright red (lighter Love)
bright2=6bafbb      # bright green (lighter Foam)
bright3=ffb65e      # bright yellow (lighter Gold)
bright4=3a9bb0      # bright blue (lighter Pine)
bright5=a690c0      # bright magenta (lighter Iris)
bright6=ec9d99      # bright cyan (lighter Rose)
bright7=726f8c      # bright white (lighter Text)
```

---

I also noticed that the Pine color is [assigned](https://github.com/EuCaue/foot/blob/main/rose-pine-dawn#L12) an [incorrect](https://rosepinetheme.com/palette/ingredients/) value for the `-dawn` theme variant, it should actually be slightly darker.

**Comment by EuCaue** [comment]
> I was skimming through the other themes and `man 5 foot.ini` to check for any additional missing colors, and there’s at least one:
> 
> ```ini
> [color]
> flash=7f7f00
> ```
> 
> This only activates when the following option is enabled (default is `no`):
> 
> ```ini
> [bell]
> visual=yes
> ```
> 
> It could still be useful to assign a value for it. Since the default uses a yellowish tone, setting it to something like Gold seems like it would fit well.
> 
> Other color values are configurable, but most already draw from the existing palette (`regular1..7`), like:
> 
> ```ini
> [color]
> selection-foreground=
> selection-background=
> jump-labels=
> scrollback-indicator=
> search-box-no-match=
> search-box-match=
> urls=
> ```
> 
> For `dim0..7`, foot has an internal algorithm to derive these from `regular0..7`:
> 
> > By  default,  foot  implements  this  by  reducing  the  luminance of the current color. This is a generic approach that applies to both colors from the 256-color palette, as well as 24-bit RGB colors.

I didn’t know `flash=` was a color option, since I’ve never used the flash feature, so it’s great to have it on the radar now! =)

I think foot should handle most of the other colors well on its own!

**Comment by EuCaue** [comment]
> I feel like this could be the end result
> 
> **Rose Pine** ![screenshot-2024-11-01-02-57-10](https://private-user-images.githubusercontent.com/18328279/382136425-465cb3d6-4004-44be-b5ee-00d62c28cf80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NzU0NjksIm5iZiI6MTczMDU3NTE2OSwicGF0aCI6Ii8xODMyODI3OS8zODIxMzY0MjUtNDY1Y2IzZDYtNDAwNC00NGJlLWI1ZWUtMDBkNjJjMjhjZjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE5MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMjZmZWY5MmFmY2Q4NGIxYmRlMmE1NDE4MDdiOGYzYWQyNWU2YmM0OWM3NWYzNmY0MDJjN2ZiOWIyOGY3MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s1AIOk8qIfoveB41v3ygO2dr1l6mxDBeDSvIRsNscCo)
> 
> ```ini
> bright0=3b3750      # bright black (lighter Overlay)
> bright1=f48fa6      # bright red (lighter Love)
> bright2=b6e2eb      # bright green (lighter Foam)
> bright3=ffd89a      # bright yellow (lighter Gold)
> bright4=4b93b0      # bright blue (lighter Pine)
> bright5=d7b7f4      # bright magenta (lighter Iris)
> bright6=ffcecc      # bright cyan (lighter Rose)
> bright7=f5f4ff      # bright white (lighter Text)
> ```
> 
> **Rose Pine Moon** ![screenshot-2024-11-01-02-57-20](https://private-user-images.githubusercontent.com/18328279/382136547-e68e1832-84f1-4313-b612-e55e25ebb28f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NzU0NjksIm5iZiI6MTczMDU3NTE2OSwicGF0aCI6Ii8xODMyODI3OS8zODIxMzY1NDctZTY4ZTE4MzItODRmMS00MzEzLWI2MTItZTU1ZTI1ZWJiMjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE5MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MWU0MzQyYmQ2ZmQwNzU2MGU2YWI1ZTM3Y2ExMjYwODY2ZjEzYWVmYjFmNjhlOGUxODdkYzQxOWJjODdkNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MSG3E5Ehp-9n7-t-AOCRgQMs_UFyoXVZfcFAhcjRPf8)
> 
> ```ini
> bright0=52486a      # bright black (lighter Overlay)
> bright1=f48fa6      # bright red (lighter Love)
> bright2=b6e2eb      # bright green (lighter Foam)
> bright3=ffd89a      # bright yellow (lighter Gold)
> bright4=5aa8cd      # bright blue (lighter Pine)
> bright5=d7b7f4      # bright magenta (lighter Iris)
> bright6=ffb1af      # bright cyan (lighter Rose)
> bright7=f5f4ff      # bright white (lighter Text)
> ```
> 
> **Rose Pine Dawn** ![screenshot-2024-11-01-02-57-32](https://private-user-images.githubusercontent.com/18328279/382136560-9bd2c524-68be-4211-9f73-6232bb102ce7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NzU0NjksIm5iZiI6MTczMDU3NTE2OSwicGF0aCI6Ii8xODMyODI3OS8zODIxMzY1NjAtOWJkMmM1MjQtNjhiZS00MjExLTlmNzMtNjIzMmJiMTAyY2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE5MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYzRjMDhlMTlkZjA5ZjMyNWIxMjVjYTYzMWE0MzM1ZmRhZTM4NjBiOTc4MmE5YzcyMTM2MTk2OWE4ZjVjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gnBwUcr9AyePgUYZv1YEmLBxuE26GCmCd85c0gDnq-8)
> 
> ```ini
> bright0=f7f1eb      # bright black (lighter Overlay)
> bright1=c97c8d      # bright red (lighter Love)
> bright2=6bafbb      # bright green (lighter Foam)
> bright3=ffb65e      # bright yellow (lighter Gold)
> bright4=3a9bb0      # bright blue (lighter Pine)
> bright5=a690c0      # bright magenta (lighter Iris)
> bright6=ec9d99      # bright cyan (lighter Rose)
> bright7=726f8c      # bright white (lighter Text)
> ```
> 
> I also noticed that the Pine color is [assigned](https://github.com/EuCaue/foot/blob/main/rose-pine-dawn#L12) an [incorrect](https://rosepinetheme.com/palette/ingredients/) value for the `-dawn` theme variant, it should actually be slightly darker.

Yes, this is a great result, I like the "lighter" variants! =D

But just to confirm, these won’t replace the main themes, right?
They’ll be something like rose-pine-main-lighter?

**Comment by EuCaue** [comment]
> I also noticed that the Pine color is [assigned](https://github.com/EuCaue/foot/blob/main/rose-pine-dawn#L12) an [incorrect](https://rosepinetheme.com/palette/ingredients/) value for the -dawn theme variant, it should actually be slightly darker.

Thanks for pointing that out! I’ll fix it! =)

**Comment by d2718nis** [comment]
> But just to confirm, these won’t replace the main themes, right?

Correct, these new colors are simply `bright` options for the existing `regular` colors, so they won’t replace or alter the main colors in the theme. They’ll just add an additional set of `bright` variants, as specified in the [ANSI standard](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit).

By default, the `foot` terminal doesn’t use these `bright` variants directly (`bold-text-in-bright` is set to `no` by default; see the [foot manual](https://man.archlinux.org/man/extra/foot/foot.ini.5.en)). Historically, they were used as a "bold" variant to add emphasis, though most modern terminals now offer multiple font weights.

These lighter variants, however, expand the terminal’s color palette and can be used by applications like [Taskwarrior](https://taskwarrior.org/).
![screenshot-2024-11-03-13-44-01](https://github.com/user-attachments/assets/3f62e15f-b261-41d6-afd6-58ba1e576460)

So, the goal was to extend the existing themes, not to create new theme variants — unless keeping `bright` the same as `regular` is an intentional principle you’re aiming to maintain.

**Comment by d2718nis** [comment]
Anyway, I went ahead and created a PR #8 with the proposed changes to help keep things moving. I’m open to discussing the `bright` color variants if you feel that’s not the right direction for this theme. Otherwise, feel free to merge the changes. Thanks!

**Comment by EuCaue** [comment]
I think it would be best not to override the default colors from the `rose-pine` palette directly in the original file, as it could be a bit confusing. Separating them into different files might make things clearer, especially for anyone who just wants the default colors. But it's definitely a great addition! =D

**Comment by d2718nis** [comment]
Sure, I'll move them to separate files then. Something like `rose-pine-extended`. I'll ping you in the PR when it's done

**Comment by d2718nis** [comment]
Hi @EuCaue! Just following up on the PR #8 and wanted to check if you'd had a chance to look it over yet. I know you mentioned being busy with university, so no worries if that’s still the case.

If maintaining the repo is tough with your current schedule, I'd be happy to help by forking and updating it in the Rose-Pine collection. Let me know if you’d be open to that, or if there's anything else I can do to move this forward. Thanks again!

**Comment by EuCaue** [comment]
Hey! =D
I merged #8, thanks for all your contributions!! =D

**Would you be interested in maintaining** it if you actively use [foot](https://codeberg.org/dnkl/foot/) and plan to keep using it? Since I don't use it anymore, I might not notice if any changes break the color scheme. =]

**Comment by d2718nis** [comment]
@EuCaue sure, no problem! I totally understand how schedules can get packed. Thanks for merging the PR — I’m happy to finally cross it off my list! =P

I’d love to take on maintaining the project! I’m using `foot` daily, and I also have a couple of Rosé Pine themes I’ve created for other tools, so it’ll be great to keep things up to date.

**Comment by d2718nis** [comment]
Will do, thank you for entrusting me with it! :)

**Comment by d2718nis** [comment]
Hey @EuCaue,

I've been thinking — if it's not too much trouble, would it be possible to transfer the ownership of this repository as described in the [official documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account)? This way, the issue history could be preserved, and the old location would automatically redirect to the new one.

If that's too much hassle, I’d be happy to submit a pull request adding a repository transfer notice instead, and then you could [archive the repository](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#archiving-a-repository) if that works for you.

Let me know which option you prefer. Thanks!

**Comment by EuCaue** [comment]
Yes, that's exactly what I was planning to do! =D 

I'll transfer the ownership to you then! =)

**Comment by EuCaue** [comment]
![image](https://github.com/user-attachments/assets/3698f266-2f18-4bcc-bc36-c15721bbadf6)

It's giving me this error. =(

I think it's because you have a fork of the repository?

**Comment by d2718nis** [comment]
@EuCaue oh right, just removed my fork. You should be able to proceed with it now

**Comment by d2718nis** [comment]
@EuCaue seems like it worked, I'm closing this issue then. Thanks!
